### ISSUE TITLE
Incomplete data for ticker RDS-A

### ISSUE THREAD

**Issue by ghost** [msperlin/BatchGetSymbols#12]
The function `BatchGetSymbols::BatchGetSymbols()` doesn't retrieve all the available data from Yahoo Finance for the ticker RDS-A (Royal Dutch Shell plc).

The following code using `quantmod::getSymbols()` seems to retrieve all the available data as we can see in [https://finance.yahoo.com/quote/RDS-A?p=RDS-A&.tsrc=fin-srch](https://finance.yahoo.com/quote/RDS-A?p=RDS-A&.tsrc=fin-srch)

```
quantmod::getSymbols(
    Symbols = 'RDS-A',
    from = '1990-01-01',
    to = '2019-07-18',
    auto.assign = FALSE
)
``` 

But the following code using `BatchGetSymbols::BatchGetSymbols()` retrieves only data from 2018-01-02 to 2019-07-18

```
BatchGetSymbols::BatchGetSymbols(
    tickers = 'RDS-A',
    first.date = '1990-01-01',
    last.date = '2019-07-18',
    thresh.bad.data = 0
)
```

**Comment by ghost** [comment]
I gave it a try a second time and now both solutions give the right answer. This may be a problem of yahoo api or I am just tired.

Feel free to close the issue if you fail to replicate the problem

**Comment by msperlin** [comment]
Thanks for the info. 

Best kind of issue, the ones that solve themselves.
