### ISSUE TITLE
combine with getquote

### ISSUE THREAD

**Issue by ahcyip** [msperlin/BatchGetSymbols#15]
Suggestion: in addition to historical data, also get the latest data from the current day.
Here is my code for that:

    l.out$df.tickers <- l.out$df.tickers %>% bind_rows(tickers %>%
      getQuote() %>%
      rownames_to_column("ticker") %>%
      transmute(ticker = ticker,
                price.open = Open, price.high = High, price.low = Low,
                price.close = NA, volume = Volume, price.adjusted = Last,
                ref.date = as.Date(`Trade Time`),
                ret.adjusted.prices = NA, ret.closing.prices = NA))

**Comment by msperlin** [comment]
Thanks ahcyip.

I thought about it and fell this implementation is not aligned with the objective of the package. If the user gets the current quote, queries throughout the day will yield different results. 

Also, I'm not sure what the user can do with 15 minutes delayed quotes..

Best,

**Comment by ahcyip** [comment]
true, it would mess up the cache!
