### ISSUE TITLE
Error with google-style check

### ISSUE THREAD

**Issue by SIA-RSS** [msperlin/BatchGetSymbols#2]
Hello there! Great package however I keep getting the following error (which will only be triggered by certain stocks)

Error in if (any(tickers.src == "google")) { : missing value where TRUE/FALSE needed

I tried to clear the options for SymbolLookup but I can't get rid of the error. It is my understanding that google no longer provide access to stock data so I'm not sure that someone will still use google-style symbols

Any help would be appreciated :)

**Comment by msperlin** [comment]
H. You're right, "google" is no longer available. I'll remove the option in the next update.
Thanks.

**Comment by SIA-RSS** [comment]
Actually... just figured out the issue... my stock list had some NAs.
Might be worth checking for NAs when creating tickers.src, that was triggering the error

:)

**Comment by msperlin** [comment]
I'll check it as soon as possible. NAs shoudl'nt be a problem.

**Comment by SIA-RSS** [comment]
What I meant is that if the stock list had NAs, tickers.src will also have NAs which will trigger the error when trying to evaluate " if (any(tickers.src == "google")) "

**Comment by msperlin** [comment]
I just pushed the changes. Added a control line as:

`
# check for NA
  if (any(is.na(tickers))) {
    my.msg <- paste0('Found NA value in ticker vector.',
                     'You need to remove it before running BatchGetSymbols.')
    stop(my.msg)
  }
`
