### ISSUE TITLE
Unrecognized backslash escape

### ISSUE THREAD

**Issue by robson-cruz** [msperlin/BatchGetSymbols#21]
Hello Mr. Perlin,
I want to congratulate you on this useful package.
I have a problem and I would like you to help me to solve it. Please.
![error_BatchGetSymbols](https://user-images.githubusercontent.com/22680143/100294887-e5974d80-2f66-11eb-8bb3-b9a00b0a2b1f.PNG)

**Comment by msperlin** [comment]
Hi rcflorestal, can you please post your code? Otherwise I can't reproduce the problem..

**Comment by msperlin** [comment]
Issue fixed. Please reinstall the pkg and it should now work.

**Comment by msperlin** [comment]
New ver going to Cran..

**Comment by robson-cruz** [comment]
Thank you so much! Now I got successes.
