### ISSUE TITLE
Error: Input must be a vector, not NULL

### ISSUE THREAD

**Issue by tedtoal** [msperlin/BatchGetSymbols#24]
If BatchGetSymbols is not able to get data for ANY of the symbols provided, it gives an error "Error: Input must be a vector, not NULL", which occurs on this statement in the function:

    df.tickers$ret.adjusted.prices <- calc.ret(df.tickers$price.adjusted, df.tickers$ticker, type.return)

At that point, df.tickers is an empty tibble.

**Comment by msperlin** [comment]
Hi Ted,

Can you please post an example of code so that I can reproduce the issue?

**Comment by tedtoal** [comment]
> symbols = "ALTAF"
    > cache.folder = file.path(tempdir(), 'BGS_Cache')
    > first.date = Sys.Date()
    > last.date = first.date+1
    > l.out = BatchGetSymbols(symbols, first.date, last.date, freq.data="daily",
    +     do.complete.data=TRUE, do.fill.missing.prices=FALSE, cache.folder=cache.folder,
    +     be.quiet=FALSE)

    Running BatchGetSymbols for:
       tickers =ALTAF
       Downloading data for benchmark ticker
    ^GSPC | yahoo (1|1) | Found cache file
    ALTAF | yahoo (1|1) | Found cache file - Error in download..Error: Input must be a vector, not NULL.
    Run `rlang::last_error()` to see where the error occurred.
    In addition: Warning messages:
    1: Unknown or uninitialised column: `ticker`. 
    2: Unknown or uninitialised column: `threshold.decision`. 
    3: Unknown or uninitialised column: `ticker`. 
    4: Unknown or uninitialised column: `ticker`. 
    5: Unknown or uninitialised column: `price.adjusted`. 
    >

**Comment by msperlin** [comment]
Your ticker, ALTAF, doesn't exist in yahoo finance. Try:

`symbols = c("FB", 'ALTAF')`

And it will work. 

I'll find a better error message for these cases of missing data for single asset..

**Comment by tedtoal** [comment]
I don't think it should be an error, just a warning.  After all, it is not an error if some symbols are missing and some are present in yahoo finance.

Actually, BatchGetSymbols() WAS able to get data for ALTAF, but only if I used an earlier date.  I assume maybe it is on an exchange that has already closed on this day.  My program tries to get a bunch of symbols for the current date, and for any that fail, it tries again one day earlier, repeating until it either has all symbols or has tried up to 7 days back.  But it was crashing because of the error message.  I got around that using tryCatch.

**Comment by tedtoal** [comment]
The problem that causes the error is that it tries to do some additional work with the symbols that it did get info for, but since there were none, it was using an empty tribble and that caused the error.  It should check for an empty tribble at that point and just skip that code.

**Comment by msperlin** [comment]
Hi ted, try using my new project yfR (https://github.com/msperlin/yfR), which is the substitute of BatchGetSymbols.
