### ISSUE TITLE
bmfbovespa access denied

### ISSUE THREAD

**Issue by apclark66** [msperlin/BatchGetSymbols#25]
Não consigo receber GetIbosStocks(), acesso não esta sendo permitido

**Comment by msperlin** [comment]
Oi,

Tentei arrumar mas, aparentemente, puxar os dados da B3 não é mais possível. 
Infelizmente não tenho uma alternativa. 

Adicionei um warning a função.

At,

**Comment by msperlin** [comment]
vou deixar o issue aberto para se, no futuro, eu consertar.

**Comment by apclark66** [comment]
Marcelo

Me orienta a transformar um acts em data frame

Insiste aí para retomar que o seu esquema de pegar dados e excepcional meu

Um abraço 

Alberto

**Comment by msperlin** [comment]
Hi, try using my new project yfR (https://github.com/msperlin/yfR), which is the substitute of BatchGetSymbols.
