### ISSUE TITLE
BMF BOVESPA não encontrado 

### ISSUE THREAD

**Issue by andreltr** [msperlin/BatchGetSymbols#26]
Olá,

O site "http://bvmf.bmfbovespa.com.br/indices/ResumoCarteiraTeorica.aspx?Indice=IBOV&idioma=pt-br" não pode ser encontrado na chamada df_ibov <- GetIbovStocks().

Suponho que isto é devido à mudança para B3 ocorrida há algum tempo. 

Como alterar essa configuração, por favor?

Obrigado,

André Luiz

**Comment by msperlin** [comment]
Andre, olha a função yfR::yf_get_index_comp("IBOV") do pacote yfR (nova versão do BatchGetSymbols).

Sugiro parar de usar o BatchGetSymbols (vou substituí-lo em breve).

**Comment by msperlin** [comment]
https://github.com/msperlin/yfR

**Comment by andreltr** [comment]
Olá Marcelo,

Obrigado! yfR já está no repositório do R também?

**Comment by msperlin** [comment]
nao, ainda não está no CRAN, somente github. 

No readme tem instruções de instalação.

**Comment by andreltr** [comment]
Obrigado.
