### ISSUE TITLE
Error in charToDate(x)

### ISSUE THREAD

**Issue by SIA-RSS** [msperlin/BatchGetSymbols#3]
For random stocks the function is not able to convert the date-string properly and will throw this error
Error in charToDate(x) :  character string is not in a standard unambiguous format.

The error is hard to troubleshoot as the error does not occur always withe the same stocks. I tried the option do.cache=F and it works if the chaced data is somewhat affected, but it doesn't solve the problem all the time... 

I still haven't figured out what's going on here...

**Comment by msperlin** [comment]
It is an issue with the caching system. When no data is return, the cache file was still created. 

The new update I released yesterday should fix it. 

To solve it, just delete the cache folder and try again. Let me know if it works.

**Comment by SIA-RSS** [comment]
Thanks, where's the cache folder located by default?

**Comment by msperlin** [comment]
A folder called "BGS_Cache" should have been created in your working directory.
