### ISSUE TITLE
Error in charToDate(x)

### ISSUE THREAD

**Issue by kevlim83** [msperlin/BatchGetSymbols#4]
Hi,

In the latest github release, I have been experiencing problems with retrieving some stock prices. 

Following #3, the issue described seems to be related to caching. However, the problem persists even after caching was turned off and no cache folder was created.

E.g.
On my system this works:
`getSymbols("BKZ.SI")`

But this does not work:
`BatchGetSymbols("BKZ.SI")`

Returned error:

> BKZ.SI | yahoo (1|1) | Not CachedError in charToDate(x) : 
  character string is not in a standard unambiguous format

In the past, I can use BatchGetSymbols with no issues 100% of the time. Now, due to this, I often have to manually remove stock tickers that are causing problems one by one, which defeats the purpose of the original idea of using BatchGetSymbols.

Any ideas how to resolve this?

Thanks :)

**Comment by msperlin** [comment]
Hi Kevin,

I just tried it here and it worked fine. I noticed, however, that the asset did not have enough data for the output. Try deleting all cache folder, run it again and let me know how it goes. 

> BatchGetSymbols("BKZ.SI")

Running BatchGetSymbols for:
   tickers = BKZ.SI
   Downloading data for benchmark ticker | Not Cached
BKZ.SI | yahoo (1|1) | Not Cached - Got 15.0% of valid prices | OUT: not enough data (thresh.bad.data = 75.0%)$df.control
  ticker   src download.status total.obs perc.benchmark.dates
1 BKZ.SI yahoo              OK         3                 0.15
  threshold.decision
1                OUT

$df.tickers
 [1] price.open          price.high          price.low          
 [4] price.close         volume              price.adjusted     
 [7] ref.date            ticker              ret.adjusted.prices
[10] ret.closing.prices 
<0 rows> (or 0-length row.names)
