### ISSUE TITLE
Company and tickers headers are interchanged in GetSP500Stocks()

### ISSUE THREAD

**Issue by zecaclasher** [msperlin/BatchGetSymbols#9]
**Problem**

The company and tickers headers are interchanged in the output from **_GetSP500Stocks()_**. So if we use the results as input for **_BatchGetSymbols()_** by using the header "tickers", we actually get the company name. Consequently, the download from Yahoo will fail.

I've got a pull request ready to come out soon, there only needs  a change between the two headers in _**line 42**_  of the script **_GetSP500Stocks.R_**.

Most likely, the wikipedia page was changed recently causing this bug.

**Expected behavior**

The function should retrieve the tickers information in the proper order as not to confuse users even though the required information is still inside the dataframe but in another column.

`my.tickets <- GetSP500Stocks()$tickers
`

**BatchGetSymbols version**

2.5.3

**Comment by msperlin** [comment]
Thank you!
